### PR TITLE
Addressing Issue #42, adding wildcard to log files access.

### PR DESCRIPTION
**Pull request by aalloilla**
Issue #42 fix suggestion.

### CODE REVIEW

**Comment by callumrollo** [comment]
Nice PR! A couple of things to fix:
1. Make a `wildcard_fname` kwarg like `  df_nginx = _load_nginx_logs(nginx_logs_dir, wildcard_fname="*access.log*")` with a sensible default. This way it should run as standard (and also won't trip up the tests!)
2. Don't run jupyter notbooks before commiting, it adds a lot of noise to the PR and a lot of unneeded baggage to git history, especially when generating images

**Comment by callumrollo** [comment]
Almost! Want the kwarg in the class definition line: `def oad_nginx_logs(self, nginx_logs_dir: str, wildcard_fname="*access.log*")`

My bad, I wrote it in the wrong line in the example I gave in my last comment ><

**Comment by callumrollo** [comment]
You should be able to run pytest locally too to test out changes before commiting

**Comment by aalloilla** [comment]
Sorry didn't get to run the tests locally. I have been too distracted by other things honestly. Thank you for your patience!

**Comment by callumrollo** [comment]
This resolved #42

**Pull request merged**
